### ISSUE TITLE
Function Errors :(

### ISSUE THREAD

**Issue by Ahmetgnczl** [nicolaskruchten/pivottable#874] opened 2018-02-27 06:41 UTC
Hi !
My English is weak  :(

I get this kind of error in my use 
What's the solution

![screencapture-localhost-56110-container-monthlystockreport-1519656744435](https://user-images.githubusercontent.com/36701116/36714224-5bb472a8-1ba2-11e8-98d7-e049a94168f3.png)

**Comment by Ahmetgnczl** [comment] 2018-02-27 11:36
Hi
 this is the perfect thing but there are problems with linq js
Resolve the Problem :)

**Comment by nicolaskruchten** [comment] 2018-02-27 18:22
Duplicate of #708 ... I don't have a fix for this yet.

**Closed** 2018-05-24 20:12 UTC
