### ISSUE TITLE
The chart area re-sizes to table size unwantedly

### ISSUE THREAD

**Issue by sunnypatel165** [nicolaskruchten/pivottable#285] opened 2015-01-20 12:43 UTC
Lets view this step-wise.
<ol>
<li> when i open my page ie the default view:

![untitled](https://cloud.githubusercontent.com/assets/9017668/5817135/99f04a1c-a0ce-11e4-85ce-645c30cb02e9.png)
</li><li>
Say, i select some columns and rows and view tables and charts all cool till now.
![untitled](https://cloud.githubusercontent.com/assets/9017668/5817170/d68bacfa-a0ce-11e4-9ea9-51b79537aaa8.png)
graph for the same set of rows and columns 
![untitled](https://cloud.githubusercontent.com/assets/9017668/5817178/f7677f30-a0ce-11e4-9068-ae266c30f5ea.png)
</li><li>
perfect till now?
 Now I select a column which produces MANY rows.
(observe the scroll bar to realize the size of the table)
![untitled](https://cloud.githubusercontent.com/assets/9017668/5817188/309b183e-a0cf-11e4-88c1-bb998fda40ab.png)
</li><li>
Now, i change my renderer to Bar chart.. see the size of the bar chart?
(again see the scroll bars and size of the image)
![untitled](https://cloud.githubusercontent.com/assets/9017668/5817198/6072bfa8-a0cf-11e4-9241-d715314bc410.png)
</li></ul>

I think that when a large table is produced, the problem occurs because of re-sizing of div, is it?
Also tested on chrome, firefox and IE. Same for all.

**Comment by nicolaskruchten** [comment] 2015-01-25 03:18
This is rather strange... I can't reproduce this with the examples here on Chrome on OSX. What operating system are you using? Are you able to reproduce this with this URL? http://nicolas.kruchten.com/pivottable/examples/gchart.html (adding the "name" as a row will give you a long table)

**Comment by sunnypatel165** [comment] 2015-01-25 03:59
I am on windows 8.1 and latest chrome. Also reproduced this on a friend's mac though.

No, your example doesn't produce the same result, but again my data seems to be much larger than "name" column in your example.

**Comment by nicolaskruchten** [comment] 2015-01-25 04:08
I suspect something else in the document is causing this behaviour, as I've never seen it on any size of data...

**Comment by sunnypatel165** [comment] 2015-01-25 04:09
Any idea/hints what could this be?
Please keep this open so that if someone has similar issues, can report.

**Comment by nicolaskruchten** [comment] 2015-01-25 04:11
If you can post an example somewhere which displays this behaviour (or even provide me with some fake data that I can load into the Local CSV example) then I can help you debug it, otherwise I'm not sure what I can do to help, given that I can't reproduce it...

**Comment by sunnypatel165** [comment] 2015-01-25 04:21
Sure, i can share with you the JSON file, please give me your email ID.. I cant publish it on web so. :)

**Comment by nicolaskruchten** [comment] 2015-01-25 14:08
nicolas@kruchten.com

**Comment by nicolaskruchten** [comment] 2015-02-11 03:14
Are you still unable to reproduce this? If so, can I close this issue?

**Closed** 2015-02-24 18:33 UTC

**Comment by nicolaskruchten** [comment] 2015-05-12 15:15
I reproduced this issue (finally) and pushed a fix :)

**Comment by sunnypatel165** [comment] 2015-05-12 15:28
Hahah finally! May I know what was the issue?

**Comment by nicolaskruchten** [comment] 2015-05-12 15:31
The charts were sizing based on the window size rather than the viewport size...

**Comment by sunnypatel165** [comment] 2015-05-12 15:33
Oh. Alright. thanks a lot man:)
