### ISSUE TITLE
Functions are written on the html table

### ISSUE THREAD

**Issue by midoo1992** [nicolaskruchten/pivottable#1149] opened 2019-09-09 15:45 UTC
I have integrated pivottable.js on my web application. It works perfectly but there are functions that are written on the first column, rows of the html table.
This is my code:

```
<script type="text/javascript" src="./jquery-1.11.0.min.js"></script>
<script type="text/javascript" src="./jquery-ui.min.js"></script>
<script type="text/javascript" src="./jquery.ui.touch-punch.min.js"></script>
<script type="text/javascript" src="./pivot.min.js"></script>
<script type="text/javascript" src="./tips_data.min.js"></script>

<link rel="stylesheet" href="./pivot.min.css">


<script type="text/javascript">
jQuery.noConflict();
jQuery(document).ready(function($) {
  $("#output").pivotUI(
    $.pivotUtilities.tipsData, {
      rows: ["sex", "smoker"],
      cols: ["day", "time"],
      vals: ["tip", "total_bill"],
      aggregatorName: "Sum over Sum",
      rendererName: "Heatmap"
    });
});

</script>

<div id="output"></div>
```
And this is a screen shot of functions that are displayed on my table
![pivot_table](https://user-images.githubusercontent.com/13468108/64545720-2898e100-d321-11e9-8241-430daee9db1d.png)

![pivot](https://user-images.githubusercontent.com/13468108/64545597-f0919e00-d320-11e9-9ea0-4ec3547ff67e.png)

**Comment by PatrickSummons** [comment] 2019-11-25 09:02
I have the exact same problem, without looking too deep i found that the last version that works for me is the 2.5.0, so you should try to change the version that you are using.

**Comment by midoo1992** [comment] 2019-12-09 15:02
HI PatrickSummons
Can you help me more ?
Can you post your code here please or how to download the version 2.5.0 of pivottable.

**Comment by nicolaskruchten** [comment] 2019-12-24 02:22
This is actually a duplicate of #708

**Closed by nicolaskruchten** 2019-12-24 02:22 UTC
