### ISSUE TITLE
Server side model - at least the core aggregators

### ISSUE THREAD

**Issue by bluechips23** [nicolaskruchten/pivottable#150] opened 2014-03-26 20:20 UTC
Hi Nicolas,

The pivot table is awesome for few hundred thousand rows and/or columns, but do you know of any open source libraries (for java that provide the ability to do some of the computation on server side?

For example, if the dataset is too big (in terms of millions of rows and columns), then some of the aggregators can be on the server side (may be as a node module or java servlet). Then we can write an API call from the pivot table to get the results from the server and display it on the browser (instead of having pivot.js do all the computation to speed up the process).

I will be exploring this more on my own, but I am curious if you have done any research about it or have any experience regarding this.

Thanks.

**Comment by philliproso** [comment] 2015-01-15 08:19
I don't think you need to do this via node.js and Phantom.js, The server could return a pre processed pivotData json object. Containing the calculated tree and totals properties. The aggregator objects attached to the pivotData object would just contain calculated values.  This light weight pivotData object containing only answers could then be seamlessly passed to one of the renderers.  On the server side the values in the pivotData object could calculated using sql or python pandas groupby statements or even other big data tools. You would need to rewrite all the aggregators in whatever server side model you where using.

**Comment by akhileshtiwari123** [comment] 2015-01-23 08:56
Hello Nicolas
can i use pivot table with amchart js?

Thanks

**Comment by thierryPopay** [comment] 2015-03-19 18:39
Indeed, that's how we do it. The json is generated and prepared in the Oracle database, and consumed by pivotTable. 

One issue we have is that the filters do not seem to work, but will dive into that later.

**Comment by oladaniel** [comment] 2015-04-16 11:51
thierryPopay, any chance you are willing to share your code?

I am trying to solve a similar problem where aggregating on the server side works best, would be nice to simply use pivotTable to display the data

**Comment by thierryPopay** [comment] 2015-04-18 07:53
Hi oladaniel, the code that generates the json is written in Oracle plsql, and is basically a bunch of sql statements, specific to our domain. So that part is not generic at all.

**Comment by tafia** [comment] 2015-08-18 06:34
I'm interested into this as well.
Can you at least give some guidance to explain what you did?

**Comment by eformx** [comment] 2015-09-12 03:24
As for the filtering and grouping on the server...I have an application at http://SankeyBuilder.com where users upload tab separated files.  Some of them are large (50k records). Before the tool creates the D3.js Sankey visualization, it takes the original file and dumps the data into a asp.net datatable where it is filtered and grouped on the fly (on the server).  The result from the in memory datatable is then saved into a TSV file and passed to D3 to create the visualization...We can do the same thing with this library.  The datatable does have a limit; however in asp.net you can create SQL Server tables on the fly, where you can append the data from the TSV file and then group and sum vales, dump the summarized view into a new TSV file for the pivotTable. Hope that helps. Rob

**Comment by m1sta** [comment] 2015-09-20 10:34
The npm module "cheerio" replicates much of the jQuery api without having a fully featured DOM. As a result it is much faster than DOM based options.

**Comment by m1sta** [comment] 2015-09-20 10:37
I'd love to see this feature progress because it might allow for the implementation of some interesting server-enforced security options. Specifically I'd like to be able to setup a system whereby certain users can only view data at a high level of detail.

**Comment by vanderlee** [comment] 2016-12-01 13:30
I really like this project, but without server integration, it's pretty much useless for any practical applications I can think of. So I'd like to invest some time in finding a solution.

If there is a single point in the code where the data requirements are known, just prior to starting the processing, a callback might be injected at that point to allow a user to provide processed data.

As far as I can tell, the required information at that point would need to include just the following:

1. Column names whose values are required by the aggregator.
2. Column names which appear above and to the left of the grid. i.e.; the columns used to group.
3. Column names and values for filtering.

Am I missing anything in this list?
Does such a point exist in the code?

**Comment by nicolaskruchten** [comment] 2016-12-01 16:14
I appreciate what you want to do, even if I don't appreciate my project being called "useless", but having looked closely at this question in the past there is no such well-defined point in the code today and I believe that the changes required to get there are too invasive for me to want to tackle at the moment...

The nature of the problem is that the input data is processed twice: once in pivotUI() to scan for the metadata and once in pivot() to do the aggregations. One could imagine wrapping the data in some sort of wrapper which provided the metadata and aggregations either by scanning through an in memory object or by querying a server but this is a big change from the current API.

**Comment by nicolaskruchten** [comment] 2016-12-01 16:21
Most people get by just fine by grabbing a largish dataset from a server (e.g. 10k rows, often the summary of a much larger, say 10M-row, dataset) and loading it into the PivotTable once and then letting the client handle the last stage of aggregation. This is performant up to around 100k rows.

**Comment by vanderlee** [comment] 2016-12-01 17:10
I didn't mean to insult you :) The project is by no means useless in general, it's just that I've got to have it handle a few millions rows <i>after</i> filtering.

From looking at the code, it seems the entire PivotData object would need to be replaced by something with the same interface. Which would pretty much mean replacing a large part of the whole project; a bit much.

**Comment by nicolaskruchten** [comment] 2016-12-04 21:01
In my experience, pivoting usually happens on a much-lower-cardinality dataset than the raw, due to aggregation rather than filtering. Are you able to pre-aggregate your millions of rows a bit before passing them to the pivot table?

For example, the original use-case for this library was analyzing millions of events across weeks of time, but we only loaded a fact table which contained a few categorical dimensions, and the hour in which the even occurred. There are only about 4000 hours in 6 months, so with a few low-cardinality dimensions, and assuming that not every permutation of the dimensions occurs in every hour, you can get pretty far with 100k rows! YMMV of course.

**Comment by nicolaskruchten** [comment] 2016-12-21 15:11
This issue is fairly well addressed in the FAQ so I'm closing it: https://github.com/nicolaskruchten/pivottable/wiki/Frequently-Asked-Questions#server-side-integration

**Closed** 2016-12-21 15:20 UTC
Labels: enhancement

**Comment by nirvana-msu** [comment] 2017-09-27 09:58
I do think it would be extremely useful to have ability to perform aggregations server-side. What this means is that the UI part needs to expose an interface which you need to implement to return data. The interface should include methods that return pre-aggregated grid (given all the groupings and filters) and also methods that return distinct values to populate filter drop-downs. The current implementation that pivots all data in-browser could be just one of the possible implementations of this interface (and only one provided out of the box). The only tool that we've been able to successfully achieve this so far, is the  Jide's pivot table in java. But it would be much nicer if it was possible to do in a browser.

**Comment by nicolaskruchten** [comment] 2017-09-27 13:01
@nirvana-msu the problem is actually a bit more complicated because in order to build the UI itself we need access to the data, specifically we need to know about all the columns and all the possible values for the columns.

**Comment by nirvana-msu** [comment] 2017-09-27 13:18
Well, yes, one would need to define all available columns during initialization. And then it should loop through the fields and ask for the domain (all possible values) for each field. The server-side implementation would then pull those distinct values from wherever it stores the data, and return to UI.

**Comment by lsisoft** [comment] 2019-10-29 17:04
I intend to build something around onRefresh method. See:

https://github.com/nicolaskruchten/pivottable/wiki/Frequently-Asked-Questions#accessingsaving-pivottable-state

and

https://pivottable.js.org/examples/onrefresh.html

To me it gives enough information to initially load pivotUI with a headers only and an empty row, than on change, collect all: rows, cols and vals and bring in JSON/CSV that has the full header but only values for the used columns.

**Comment by swuecho** [comment] 2019-10-31 14:04
I found that redash use react fork of this lib and the data is from server side.

I did not look into it yet, but might be helpful to some one.

https://github.com/getredash/redash/blob/780fbceba5c95ae279d0b8aee7be6fd68b7cce3d/client/app/visualizations/pivot/Renderer.jsx

**Comment by sibelius** [comment] 2020-01-08 22:07
anybody has a repo showing how to integrate?
