### ISSUE TITLE
Smoothing/ Running Averages

### ISSUE THREAD

**Issue by 50percentDave** [nicolaskruchten/pivottable#355] opened 2015-07-14 12:13 UTC
Hi
I'm interested in producing a running average &/or smoothing via the average of a definable number of previous values (in a date series).  I could produce this via sql on the database that I'm getting the data from, but thought that this could be either a derived attribute or an aggregation function, but I'm a bit stuck on the best approach and also how to reference the values in previous cells.  Any guidance gratefully received.

Edit
It's amazing that just after posting I came across #140 which has given me something to work from.  I'll see what I can come up with.

**Comment by nicolaskruchten** [comment] 2015-07-14 18:54
OK, let me know how it goes! I think there's enough info in that other ticket to put you on the right track :)

**Comment by 50percentDave** [comment] 2015-07-17 16:23
Both of these are minor modifications of the code in #140  by philliproso

There are probably more efficient and elegant ways of doing this, but I've never used coffeescript before, so apologies in advance.

runningAverage takes account of whether some of the cells are empty or not,smoothedAverage does not

In the code for smoothedAverage, the value in a cell is the average of the current cell and the previous 3 cell values, in the earlier cells it's the average of the current cell and the previous cells.


    runningAverage: (formatter=usFmt) -> ([attr]) -> (data, rowKey, colKey) ->
      sum: 0
      push: (record) -> @sum += parseFloat(record[attr]) if not isNaN parseFloat(record[attr])
      value: ->
        colKeys=data.getColKeys()
        counter = 0
        flat_col_key=colKey.join(String.fromCharCode(0))
        for item in colKeys
          flat_item=item.join(String.fromCharCode(0))
          if flat_item is flat_col_key
            itter=counter
          counter++
          prev_value = 0
          if itter >0
            denom = 1
            for i in [1...itter+1]
              aggregator = data.getAggregator(rowKey, colKeys[itter-i])
              if 'sum' of aggregator
                prev_value += aggregator.sum
                denom++
          return (@sum + prev_value) / (denom - 1)
      format: formatter
      numInputs: 1


    smoothedAverage: (formatter=usFmt) -> ([attr]) -> (data, rowKey, colKey) ->
      sum: 0
      push: (record) -> @sum += parseFloat(record[attr]) if not isNaN parseFloat(record[attr])
      value: ->
        colKeys=data.getColKeys()
        counter = 0
        flat_col_key=colKey.join(String.fromCharCode(0))
        for item in colKeys
          flat_item=item.join(String.fromCharCode(0))
          if flat_item is flat_col_key
            itter=counter
          counter++
          for i in [1...itter+1]
            prev_value = 0
            if (itter -1) of colKeys
              aggregatorone = data.getAggregator(rowKey, colKeys[itter-i])
              if 'sum' of aggregatorone
                prev_value += aggregatorone.sum
            if (itter -2) of colKeys                    
              aggregatortwo = data.getAggregator(rowKey, colKeys[itter-(i+1)])
              if 'sum' of aggregatortwo
                prev_value += aggregatortwo.sum
            if (itter -3) of colKeys
              aggregatorthree = data.getAggregator(rowKey, colKeys[itter-(i+2)])
              if 'sum' of aggregatorthree
                prev_value += aggregatorthree.sum
            if itter > 3                              
              return ((@sum + prev_value) / 4)   
            return ((@sum + prev_value) / (5 - (4 - itter)))           
      format: formatter
      numInputs: 1

**Comment by 50percentDave** [comment] 2015-07-17 17:12
Both of these are minor modifications of the code by philliproso  in #140 

runningAverage calculates a running average of non-blank cells
smoothedAverage calculates the average of the current cell and the 3 previous cells - it doesn't take account of blank cells, or if there have been fewer than 3 previous values, the average of the current cell and it's predecessors.

There are probably lots of more efficient and elegant ways of doing this in coffeescript, but this was my first time using it, so please indulge my inefficiencies (I got part of the way there in coffeescript, hacked the resulting javascript, then tried to work out the necessary coffeescript to get that js.

Anyway I've now got node.js / npm installed so may further refine things, but it's working sufficiently for me needs

    runningAverage: (formatter=usFmt) -> ([attr]) -> (data, rowKey, colKey) ->
      sum: 0
      push: (record) -> @sum += parseFloat(record[attr]) if not isNaN parseFloat(record[attr])
      value: ->
        colKeys=data.getColKeys()
        counter = 0
        flat_col_key=colKey.join(String.fromCharCode(0))
        for item in colKeys
          flat_item=item.join(String.fromCharCode(0))
          if flat_item is flat_col_key
            itter=counter
          counter++
        prev_value = 0
        if itter >0
          denom = 1
          for i in [1...itter+1]
            aggregator = data.getAggregator(rowKey, colKeys[itter-i])
            if 'sum' of aggregator
              prev_value += aggregator.sum
              denom++
        return ((@sum + prev_value) / (denom - 1))
      format: formatter
      numInputs: 1


    smoothedAverage: (formatter=usFmt) -> ([attr]) -> (data, rowKey, colKey) ->
      sum: 0
      push: (record) -> @sum += parseFloat(record[attr]) if not isNaN parseFloat(record[attr])
      value: ->
        colKeys=data.getColKeys()
        counter = 0
        flat_col_key=colKey.join(String.fromCharCode(0))
        for item in colKeys
          flat_item=item.join(String.fromCharCode(0))
          if flat_item is flat_col_key
            itter=counter
          counter++
        for i in [1...itter+1]
          prev_value = 0
          if itter-1 of colKeys
            aggregatorone = data.getAggregator(rowKey, colKeys[itter-1])
            if 'sum' of aggregatorone
              prev_value += aggregatorone.sum
          if itter-2 of colKeys                    
            aggregatortwo = data.getAggregator(rowKey, colKeys[itter-2])
            if 'sum' of aggregatortwo
              prev_value += aggregatortwo.sum
          if itter-3 of colKeys
            aggregatorthree = data.getAggregator(rowKey, colKeys[itter-3])
            if 'sum' of aggregatorthree
              prev_value += aggregatorthree.sum
          if itter > 3                              
            return ((@sum + prev_value) / 4)   
          return ((@sum + prev_value) / (5 - (4 - itter)))           
      format: formatter
      numInputs: 1

**Comment by 50percentDave** [comment] 2015-07-19 09:41
Again, another minor modification
Percentage change from previous value

    percentageChange: (formatter=usFmt) -> ([attr]) -> (data, rowKey, colKey) ->
      sum: 0
      push: (record) -> @sum += parseFloat(record[attr]) if not isNaN parseFloat(record[attr])
      value: ->
        colKeys=data.getColKeys()
        counter = 0
        flat_col_key=colKey.join(String.fromCharCode(0))
        for item in colKeys
          flat_item=item.join(String.fromCharCode(0))
          if flat_item is flat_col_key
            itter=counter
          counter++
        if itter >0
          aggregator = data.getAggregator(rowKey, colKeys[itter-1])
          if 'sum' of aggregator
              return (((@sum - aggregator.sum)/aggregator.sum))
        return      
      format: formatter
      numInputs: 1

**Comment by nicolaskruchten** [comment] 2016-12-27 01:24
I'm going to close this as a duplicate of #140 and leave a link there to here.

**Closed by nicolaskruchten** 2016-12-27 01:24 UTC
