### ISSUE TITLE
Pivot doesn't accept exclusion and inclusions. PivotUI does.

### ISSUE THREAD

**Issue by FloPrey** [nicolaskruchten/pivottable#883] opened 2018-03-15 09:21 UTC
Hi.

I found a quite confusing issue concerning the pivot table when showing the table without configurations.
When setting the _exclusions_ and _inclusions_ attribute in the pivotUI() config element the according filters are set. Using the same config in the pivot() function for displaying just the table the result looks different.

I also created a js fiddle to show you the problem:
https://jsfiddle.net/ngw1dmtp/10/

Cheers

**Comment by nicolaskruchten** [comment] 2018-03-15 15:35
Yes, `pivot()` and `pivotUI()` do slightly different things and have slightly different input parameters: https://github.com/nicolaskruchten/pivottable/wiki/Parameters

**Comment by FloPrey** [comment] 2018-03-15 15:52
Is it possible to also accept exclusions in pivot() parameters for your next release?
At the moment I have the issue when I saving a config from the pivotUI() and display it afterwards in pivot() doesn't look the same and that makes it actually quite unhandy.

**Comment by nicolaskruchten** [comment] 2018-03-15 18:06
I'm not that interested in changing the existing behaviour of `pivot()`, no...

I've looked at creating a new function, something like `pivotNoUI()` or adding a `hideUI` parameter to `pivotUI()` but neither seemed particularly easy to do. I'd happily accept a PR for it though!

**Comment by jneilliii** [comment] 2018-06-08 21:41
That's disappointing...this is exactly what I need in my current implementation of an executive dashboard. Give the user a master pivotUI that allows them to set their options the way they want it, and then click a button to save the config, allowing multiple pivots on the same dashboard, etc.  Then when they load the dashboard page they don't need the entire UI, just the resultant pivot.

Just out of curiosity, what were they issues you ran into looking at a new function?

**Comment by nicolaskruchten** [comment] 2018-06-18 14:01
@jneilliii the issue is that `pivotUI` stores its state in the DOM, so we can't just not render those elements.

The latest release (v2.21.0) papers over this by adding `showUI` parameter that can be set to `false` to hide the UI. It literally hides the UI: the DOM elements are created but then made invisible via CSS ;)

**Comment by nicolaskruchten** [comment] 2018-06-18 14:01
The documentation has been updated in various place, so I'm closing this issue.

**Closed by nicolaskruchten** 2018-06-18 14:01 UTC

**Comment by jneilliii** [comment] 2018-06-18 15:35
Thanks, that's actually the approach I took in my application, hiding things after load. Having it built in as an option makes it much cleaner.
